// Generated by https://quicktype.io

export interface AuthResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    new?: boolean;
    uid:    string | null;
    correo: string;
    nombre: string;
    rol:    string;
    estado: boolean;
    google: boolean;
}


